INSERT INTO `people` VALUES (1, 111, 'Bilbo', 'Baggins'), (2, 33, 'Frodo', 'Baggins'), (3, 2019, 'Gandalf', 'Olórin');
INSERT INTO `shifts` (type, note, number, paid, present) VALUES ('5-2-8', 'same days off', 40, 300, 320), ('5-3-8.5+3', NULL, 38, 304, 323), ('5-3-9', NULL, 35, 297.5, 315), ('4-4-9+7', NULL, 35, 297.5, 315), ('4-4-9.5+5', NULL, 33, 297, 313.5), ('4-4-10+4', NULL, 32, 304, 320), ('4-3-10', 'same days off', 32, 304, 320), ('4-4-10.5+2', NULL, 30, 300, 315), ('4-4-11', NULL, 28, 294, 308), ('4-4-12', '1 hour lunch', 28, 308, 336);
INSERT INTO `users` (name, email, password, created_at, updated_at) VALUES ('scott', 'scott@burlresearch.com', '$2y$10$rOgGHmhZc82sOUgCYJZNee1GJqvxwAT0UbQz/eNm.LaFuZcEZlZMW', '2018-02-05 22:47:38', '2018-02-05 22:47:38'), ('mehdi', 'mehdi.tabib@cbsa-asfc.gc.ca', '$2y$10$eOIGp2.u6sn7xlXJjP/pIe00E.oYiHpXP9JaaDcXIjRDNsaV4eEqy', '2018-02-05 22:47:38', '2018-02-05 22:47:38'), ('alex', 'alexandre.desforges@cbsa-asfc.gc.ca', '$2y$10$8nl3GGzOMee5efDrT4lK2ewn7ZjjJyiCS1rH2Mf10gIkN3Ft.IOxS', '2018-02-05 22:47:38', '2018-02-05 22:47:38'), ('leo.chavez', 'sonarinfo@mail.com', '$2y$10$b81GNGwxaPOpD9Mfs5q4vOZc6XlVTo2rYIp0w6WuvGSHW4UfkfxdK', '2018-02-05 22:47:38', '2018-02-05 22:47:38'), ('leo.pu', 'leoljpu@gmail.com', '$2y$10$NFFlEmnrmn1KBQni97xRv.p9/d.9vJxxptl/DlRNhndoH8tQrBt.K', '2018-02-05 22:47:38', '2018-02-05 22:47:38');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (1, 7, '0007', 'Halifax Customs Mail Centre', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (2, 9, '0009', 'Halifax', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (3, 10, '0010', 'Kentville', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (4, 11, '0011', 'Liverpool', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (5, 13, '0013', 'Lunenburg', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (6, 15, '0015', 'New Glasgow', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (7, 19, '0019', 'Port Hawkesbury', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (8, 20, '0020', 'Shelburne', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (9, 21, '0021', 'Sydney', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (10, 22, '0022', 'Truro', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (11, 25, '0025', 'Yarmouth', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (12, 26, '0026', 'Halifax International Airport', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (13, 101, '0101', 'Charlottetown', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (14, 102, '0102', 'Summerside', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (15, 201, '0201', 'Bathurst', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (16, 202, '0202', 'Dalhousie', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (17, 204, '0204', 'Fredericton', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (18, 205, '0205', 'St.Croix', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (19, 206, '0206', 'Moncton', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (20, 207, '0207', 'Miramichi', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (21, 209, '0209', 'St. Andrews', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (22, 210, '0210', 'Saint John, New Brunswick', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (23, 211, '0211', 'St. Stephen', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (24, 212, '0212', 'Woodstock Road', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (25, 213, '0213', 'Edmundston', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (26, 214, '0214', 'Andover', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (27, 215, '0215', 'Centreville', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (28, 216, '0216', 'Clair', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (29, 217, '0217', 'Grand Falls, New Brunswick', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (30, 218, '0218', 'St. Leonard', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (31, 219, '0219', 'Gillespie Portage', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (32, 221, '0221', 'Caraquet', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (33, 224, '0224', 'Grand Manan', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (34, 225, '0225', 'Campobello', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (35, 900, '0900', 'Clarenville', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (36, 910, '0910', 'Grand Falls, Newfoundland', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (37, 911, '0911', 'Corner Brook', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (38, 912, '0912', 'Gander', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (39, 913, '0913', 'Goose Bay', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (40, 914, '0914', 'St. John''s, Newfoundland', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (41, 919, '0919', 'Fortune', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (42, 921, '0921', 'Argentia', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (43, 922, '0922', 'Harbour Grace', 'Atlantic');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (44, 301, '0301', 'Chicoutimi', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (45, 303, '0303', 'Drummondville', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (46, 304, '0304', 'Gaspé', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (47, 305, '0305', 'Granby', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (48, 307, '0307', 'Trout River', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (49, 308, '0308', 'Woburn', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (50, 312, '0312', 'Québec', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (51, 313, '0313', 'Rimouski', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (52, 314, '0314', 'Rock Island', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (53, 315, '0315', 'Shawinigan', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (54, 316, '0316', 'Sherbrooke', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (55, 317, '0317', 'Sorel', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (56, 318, '0318', 'Abercorn', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (57, 320, '0320', 'St-Hyacinthe', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (58, 321, '0321', 'St-Jean', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (59, 322, '0322', 'Trois-Rivières', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (60, 323, '0323', 'Valleyfield', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (61, 327, '0327', 'Victoriaville', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (62, 328, '0328', 'St-Armand-Philipsburg', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (63, 329, '0329', 'Armstrong', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (64, 330, '0330', 'Dundee', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (65, 331, '0331', 'Pohénégamook', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (66, 332, '0332', 'Frelighsburg', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (67, 333, '0333', 'Hemmingford', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (68, 334, '0334', 'Highwater', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (69, 335, '0335', 'St-Pamphile', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (70, 337, '0337', 'Clarenceville', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (71, 340, '0340', 'Rivière-du-Loup', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (72, 342, '0342', 'Joliette', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (73, 343, '0343', 'Lachute', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (74, 344, '0344', 'Montmagny', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (75, 345, '0345', 'Richmond', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (76, 346, '0346', 'St-Jérôme', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (77, 347, '0347', 'Thetford Mines', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (78, 349, '0349', 'Rouyn-Noranda', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (79, 350, '0350', 'Val-d''Or', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (80, 351, '0351', 'Lacolle', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (81, 354, '0354', 'Stanhope', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (82, 355, '0355', 'Baie-Comeau', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (83, 356, '0356', 'Cowansville', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (84, 361, '0361', 'Sept-Iles', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (85, 362, '0362', 'East Hereford', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (86, 363, '0363', 'Cap-aux-Meules', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (87, 365, '0365', 'Chartierville', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (88, 366, '0366', 'Hereford Road', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (89, 367, '0367', 'Morses Line', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (90, 368, '0368', 'Noyan', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (91, 369, '0369', 'East Pinnacle', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (92, 370, '0370', 'Glen Sutton', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (93, 371, '0371', 'Daaquam', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (94, 375, '0375', 'Rock Island, Rte 143', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (95, 376, '0376', 'Beebe', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (96, 395, '0395', 'Montréal Main Long Room', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (97, 396, '0396', 'Montréal International Airport (Dorval)', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (98, 398, '0398', 'Montréal Intermediate Terminal (C.D.L.)', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (99, 399, '0399', 'Mirabel International Airport', 'Quebec');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (100, 400, '0400', 'Peterborough', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (101, 402, '0402', 'Belleville', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (102, 405, '0405', 'Brockville', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (103, 409, '0409', 'Cornwall', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (104, 420, '0420', 'Kingston', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (105, 428, '0428', 'North Bay', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (106, 431, '0431', 'Ottawa (Longroom)/Sufferance', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (107, 439, '0439', 'Prescott', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (108, 441, '0441', 'Sault Ste. Marie', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (109, 444, '0444', 'Sudbury', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (110, 449, '0449', 'Trenton', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (111, 456, '0456', 'Lansdowne', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (112, 461, '0461', 'Thunder Bay', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (113, 467, '0467', 'Timmins', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (114, 469, '0469', 'Pembroke', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (115, 470, '0470', 'Perth', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (116, 473, '0473', 'Cobourg', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (117, 474, '0474', 'Smiths Falls', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (118, 475, '0475', 'Pigeon River', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (119, 477, '0477', 'Lindsay', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (120, 478, '0478', 'Fort Frances', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (121, 485, '0485', 'Ottawa Air Cargo Centre (OACC) Macdonald-Cartier International Airport (MCIA)', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (122, 488, '0488', 'Rainy River', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (123, 490, '0490', 'Kenora', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (124, 494, '0494', 'Arnprior', 'Northern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (125, 401, '0401', 'Kitchener', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (126, 404, '0404', 'Brantford', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (127, 406, '0406', 'Chatham', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (128, 410, '0410', 'Fort Erie', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (129, 414, '0414', 'Guelph', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (130, 417, '0417', 'Hamilton', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (131, 423, '0423', 'London', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (132, 424, '0424', 'Midland', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (133, 425, '0425', 'Stratford', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (134, 427, '0427', 'Niagara Falls', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (135, 429, '0429', 'Orillia', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (136, 430, '0430', 'Oshawa', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (137, 440, '0440', 'Sarnia', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (138, 442, '0442', 'Simcoe', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (139, 445, '0445', 'St. Catharines', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (140, 446, '0446', 'St. Thomas', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (141, 447, '0447', 'Tillsonburg', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (142, 448, '0448', 'Hanover', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (143, 450, '0450', 'Wallaceburg', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (144, 451, '0451', 'Welland', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (145, 452, '0452', 'Windsor Detroit/Canada Tunnel', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (146, 453, '0453', 'Windsor Ambassador Bridge', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (147, 454, '0454', 'Windsor Metro Operations', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (148, 457, '0457', 'Cambridge', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (149, 458, '0458', 'Collingwood', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (150, 459, '0459', 'Barrie', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (151, 460, '0460', 'Bracebridge', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (152, 464, '0464', 'Leamington', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (153, 465, '0465', 'Sombra', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (154, 471, '0471', 'Port Colborne', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (155, 476, '0476', 'Oakville', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (156, 480, '0480', 'Brampton', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (157, 482, '0482', 'Owen Sound', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (158, 483, '0483', 'Halton Hills', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (159, 486, '0486', 'Newmarket', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (160, 491, '0491', 'Toronto International Mail Division', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (161, 492, '0492', 'Woodstock', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (162, 495, '0495', 'Toronto Metro Operations Division', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (163, 496, '0496', 'Toronto Interport Sufferance Warehouse (Dixie)', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (164, 497, '0497', 'Toronto International Airport (Pearson)', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (165, 498, '0498', 'Toronto Mid-continent Truck Terminal (Queensway)', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (166, 499, '0499', 'Toronto Sufferance Truck Terminal (Kennedy Road)', 'Southern Ontario');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (167, 502, '0502', 'Emerson', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (168, 503, '0503', 'Gretna', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (169, 504, '0504', 'Winnipeg Main Long Room', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (170, 505, '0505', 'Sprague', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (171, 506, '0506', 'South Junction', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (172, 507, '0507', 'Boissevain', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (173, 508, '0508', 'Goodlands', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (174, 509, '0509', 'Snowflake', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (175, 510, '0510', 'Winnipeg International Airport', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (176, 511, '0511', 'Churchill', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (177, 512, '0512', 'Inuvik', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (178, 513, '0513', 'Iqaluit', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (179, 514, '0514', 'Tuktoyaktuk', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (180, 515, '0515', 'Yellowknife', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (181, 516, '0516', 'Tolstoi', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (182, 517, '0517', 'Piney', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (183, 518, '0518', 'Winkler', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (184, 519, '0519', 'Windygates', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (185, 522, '0522', 'Lena', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (186, 601, '0601', 'Moose Jaw', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (187, 602, '0602', 'North Portal', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (188, 603, '0603', 'Prince Albert', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (189, 604, '0604', 'Regina', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (190, 605, '0605', 'Saskatoon', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (191, 607, '0607', 'Regway', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (192, 612, '0612', 'Carievale', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (193, 613, '0613', 'Northgate', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (194, 616, '0616', 'Oungre', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (195, 617, '0617', 'Torquay', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (196, 618, '0618', 'West Poplar River', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (197, 620, '0620', 'Monchy', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (198, 621, '0621', 'Willow Creek', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (199, 701, '0701', 'Calgary', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (200, 702, '0702', 'Edmonton', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (201, 703, '0703', 'Lethbridge', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (202, 705, '0705', 'Coutts', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (203, 706, '0706', 'Aden', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (204, 707, '0707', 'Carway', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (205, 708, '0708', 'Del Bonita', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (206, 711, '0711', 'Wild Horse', 'Prairie');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (207, 801, '0801', 'Cranbrook', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (208, 803, '0803', 'Vancouver Mail Centre', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (209, 804, '0804', 'Nanaimo', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (210, 806, '0806', 'Vancouver International Marine Operations', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (211, 807, '0807', 'Penticton', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (212, 808, '0808', 'Prince Rupert', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (213, 809, '0809', 'Vancouver Main Longroom', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (214, 810, '0810', 'Vancouver Commercial Operations East', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (215, 811, '0811', 'Victoria', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (216, 813, '0813', 'Pacific Highway', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (217, 814, '0814', 'Kamloops', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (218, 815, '0815', 'Boundary Bay', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (219, 816, '0816', 'Cascade', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (220, 817, '0817', 'Huntingdon', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (221, 818, '0818', 'Kingsgate', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (222, 819, '0819', 'Osoyoos', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (223, 820, '0820', 'Prince George', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (224, 821, '0821', 'Vancouver International Airport', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (225, 822, '0822', 'Rykerts', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (226, 823, '0823', 'Vernon', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (227, 824, '0824', 'Roosville', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (228, 825, '0825', 'Port Alberni', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (229, 826, '0826', 'Powell River', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (230, 827, '0827', 'Kitimat', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (231, 828, '0828', 'Nelway', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (232, 829, '0829', 'Flathead', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (233, 830, '0830', 'Courtenay', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (234, 831, '0831', 'Kelowna', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (235, 832, '0832', 'Paterson', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (236, 833, '0833', 'Waneta', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (237, 834, '0834', 'Carson', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (238, 835, '0835', 'Midway', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (239, 836, '0836', 'Chopaka', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (240, 837, '0837', 'Sidney', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (241, 838, '0838', 'Campbell River', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (242, 839, '0839', 'Dawson Creek', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (243, 840, '0840', 'Douglas', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (244, 841, '0841', 'Aldergrove', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (245, 842, '0842', 'Roosville', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (246, 890, '0890', 'Whitehorse', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (247, 891, '0891', 'Pleasant Camp', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (248, 892, '0892', 'Beaver Creek, Yukon', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (249, 893, '0893', 'Fraser', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (250, 894, '0894', 'Dawson City', 'Pacific');
INSERT INTO `ports` (id, code, cstr, name, region) VALUES (251, 950, '0950', 'Pre-clearance operations', 'Pacific');
